<!--[if (lt IE 9) & (!IEMobile)]>
<script type="text/javascript" src="theme/js/lib/html5.js"></script>
<![endif]-->
<script type="text/javascript" src="common/js/lib/jquery.min.js"></script>
<script type="text/javascript" src="theme/js/lib/device.min.js"></script>
<script type="text/javascript" src="theme/js/lib/jquery.flexslider-min.js"></script>
<script type="text/javascript" src="theme/js/lib/select2.full.min.js"></script>
<script type="text/javascript" src="theme/js/lib/ss-social.js"></script>
<script type="text/javascript" src="theme/js/lib/ss-symbolicons.js"></script>
<script type="text/javascript" src="theme/js/lib/jquery.scrollbar.js"></script>
<script type="text/javascript" src="theme/js/js.js"></script>