<footer id="site-footer" class="site-footer">
  <div class="container">
    <div class="top-footer">
      <div class="social">
        <span class="title">Sponsored by</span>
        <ul>
          <li><a href="#"><img src="theme/images/tmp/img-logo-1.png" alt=""/></a></li>
          <li><a href="#"><img src="theme/images/tmp/img-logo-2.png" alt=""/></a></li>
          <li><a href="#"><img src="theme/images/tmp/img-logo-3.png" alt=""/></a></li>
          <li><a href="#"><img src="theme/images/tmp/img-logo-4.png" alt=""/></a></li>
        </ul>
      </div>
    </div>
    <div class="bottom-footer">
      <div class="logo"><a href="#"><img src="theme/images/logo.png" alt=""/></a></div>
      <div class="navigation">
        <ul>
          <li><a href="#">CONTACT</a></li>
          <li><a href="#">DONATE</a></li>
        </ul>
      </div>
      <div class="social-links">
        <ul>
          <li><a class="ss-social-regular ss-facebook" href="#"></a></li>
          <li><a class="ss-social-regular ss-twitter" href="#"></a></li>
          <li><a class="ss-social-regular ss-pinterest" href="#"></a></li>
          <li><a class="ss-social-regular ss-youtube" href="#"></a></li>
          <li><a class="ss-social-regular ss-instagram" href="#"></a></li>
        </ul>
      </div>
      <p class="copy">2100 NE 52nd St, Oklahoma City, OK 73111  • (405) 602-6664</p>
    </div>
  </div>
</footer>