<header id="site-header" class="site-header">
  <div class="container">
    <a class="btn-mobile" href="#"></a>

    <div class="logo">
      <a href="#">
        <img src="theme/images/logo-a.png" alt=""/>
        <img class="mobile" src="theme/images/logo.png" alt=""/>
      </a>
    </div>
    <div class="top-header">
      <div class="social-links">
        <ul>
          <li><a class="ss-social-regular ss-facebook" href="#"></a></li>
          <li><a class="ss-social-regular ss-twitter" href="#"></a></li>
          <li><a class="ss-social-regular ss-pinterest" href="#"></a></li>
          <li><a class="ss-social-regular ss-youtube" href="#"></a></li>
          <li><a class="ss-social-regular ss-instagram" href="#"></a></li>
        </ul>
      </div>
      <div class="navigation">
        <ul>
          <li><a href="#">MEMBERSHIPS</a></li>
          <li><a href="#">MAP</a></li>
        </ul>
      </div>
    </div>
    <div class="bottom-header">
      <nav class="nav">
        <ul>
          <li class="expanded"><a href="#">Guests</a>
            <ul class="menu">
              <li><a href="" title="">Admissions</a></li>
              <li class="expanded"><a href="">Location</a>
                <ul class="menu">
                  <li><a href="">Admissions1</a></li>
                  <li><a href="">Location1</a></li>
                  <li><a href="">Membership1</a></li>
                </ul>
              </li>
              <li class="expanded"><a href="">Membership</a>
                <ul class="menu">
                  <li><a href="">Admissions1</a></li>
                  <li><a href="">Location1</a></li>
                  <li><a href="">Membership1</a></li>
                </ul>
              </li>
              <li><a href="">Birthdays</a></li>
              <li><a href="">Field Trips</a></li>
              <li><a href="">Amenities</a></li>
            </ul>
          </li>
          <li class="expanded">
            <a href="#">Programs</a>
            <ul>
              <li><a href="#">SCIENCE CAMPS</a></li>
              <li><a href="#">SCIENCE OVERNIGHTS</a></li>
              <li><a href="#">CHEMISTRY DAY</a></li>
              <li><a href="#">SPACE DAY</a></li>
              <li><a href="#">OMN</a></li>
              <li><a href="#">EVENT RENTALS</a></li>
            </ul>
          </li>
          <li><a href="#">Explore the Museum</a></li>
          <li class="active"><a class="active" href="#">Outreach</a></li>
          <li><a href="#">Shows</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Support</a></li>
        </ul>
      </nav>
      <div class="navigation mobile">
        <ul>
          <li><a href="#">MEMBERSHIPS</a></li>
          <li><a href="#">MAP</a></li>
          <li><a href="#">Donate</a></li>
        </ul>
      </div>
      <div class="social-links mobile">
        <ul>
          <li><a class="ss-social-regular ss-facebook" href="#"></a></li>
          <li><a class="ss-social-regular ss-twitter" href="#"></a></li>
          <li><a class="ss-social-regular ss-pinterest" href="#"></a></li>
          <li><a class="ss-social-regular ss-youtube" href="#"></a></li>
          <li><a class="ss-social-regular ss-instagram" href="#"></a></li>
        </ul>
      </div>
    </div>
    <a class="link" href="#">Donate</a>

    <div class="btn-tickets"><a href="#"><span class="ss-ticket">GET TICKETS</span></a></div>
  </div>
</header>